# Site settings
title: Nathan Podlich
email: nathan.podlich@gmail.com
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
description: > # this means to ignore newlines until "baseurl:"
  A log of some of the things I, at some point, found interesting or
  important enough to write about or record.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.nathanpodlich.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  enpey
bitbucket_username: enpey

# Build settings
markdown: kramdown

# Markdown processors
kramdown:
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6

